"""HTTP timeouts, pool sizes, and retry policy for shared clients."""

# Timeout HTTP (giây)
YOUTUBE_API_TIMEOUT = 15
URL_SHORTENER_TIMEOUT = 10
GEOIP_LOOKUP_TIMEOUT = 5
SUPABASE_AUTH_TIMEOUT = 5
REMOTE_CONFIG_TIMEOUT = 5
HEALTH_CHECK_TIMEOUT = 3

# Connection pool data-miner
DATA_MINER_MAX_CONN = 20
DATA_MINER_MAX_KEEPALIVE = 10

# Retry HTTP
HTTP_MAX_ATTEMPTS = 3
HTTP_RETRY_STATUSES = {502, 503, 504}
