"""Data-miner HTTP client — split by domain (youtube / tiktok / movies)."""

from app.clients.data_miner._http import close_client
from app.clients.data_miner.movies import (
    movie_get_countries,
    movie_get_detail,
    movie_get_genres,
    movie_list_by_country,
    movie_list_by_genre,
    movie_list_by_type,
    movie_list_by_year,
    movie_list_new,
    movie_search,
)
from app.clients.data_miner.tiktok import (
    tiktok_comments,
    tiktok_profile,
    tiktok_search,
    tiktok_transcript,
    tiktok_video_info,
)
from app.clients.data_miner.youtube import (
    get_by_region,
    get_by_topic,
    get_channel_info,
    get_channel_playlists,
    get_channel_videos,
    get_live,
    get_playlist_videos,
    get_shorts,
    get_trending,
    get_video_comments,
    get_video_comments_batch,
    get_video_detail,
    get_video_transcript,
    get_video_transcript_batch,
    search_youtube,
)

__all__ = [
    "close_client",
    "get_by_region",
    "get_by_topic",
    "get_channel_info",
    "get_channel_playlists",
    "get_channel_videos",
    "get_live",
    "get_playlist_videos",
    "get_shorts",
    "get_trending",
    "get_video_comments",
    "get_video_comments_batch",
    "get_video_detail",
    "get_video_transcript",
    "get_video_transcript_batch",
    "movie_get_countries",
    "movie_get_detail",
    "movie_get_genres",
    "movie_list_by_country",
    "movie_list_by_genre",
    "movie_list_by_type",
    "movie_list_by_year",
    "movie_list_new",
    "movie_search",
    "search_youtube",
    "tiktok_comments",
    "tiktok_profile",
    "tiktok_search",
    "tiktok_transcript",
    "tiktok_video_info",
]
